AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  
  Exclude:
    - '_site/**/*'
    - 'src/_plugins/vendored/**/*'

    # This is to avoid RuboCop trying to lint too much stuff when running
    # in GitHub Actions.
    # See https://stackoverflow.com/a/69421161/1558022
    - 'vendor/**/*'

Layout/LineLength:
  Max: 200

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
