# ====================
# Global configuration
# ====================
#
# See https://jekyllrb.com/docs/configuration/options/#global-configuration

source: "src"
destination: "_site"

# =====================
# Build command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#build-command-options

# This enables strict parsing of the YAML front matter.
strict_front_matter: true

# =====================
# Serve command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#serve-command-options

port: 5959
livereload: true
livereload_port: 35959

# ==============
# Liquid options
# ==============
#
# See https://jekyllrb.com/docs/configuration/liquid/

liquid:
  error_mode: strict
  strict_filters: true

  # Note: I deliberately omit `strict_variables: true` here, because
  # sometimes I want to be able to skip variables in the front matter
  # (e.g. I don't want to set an empty `nav_section: ""` for every page
  # which doesn't belong to a section).

# ================
# Permalink config
# ================
#
# Set the URL structure for permalinks on my posts.
# See https://jekyllrb.com/docs/permalinks/#global
permalink: "/:year/:title/"

# ================
# Remaining config

url: "https://books.alexwlchan.net"

exclude:
  - "covers"

keep_files:
  - "favicons"
  - "individual_covers"
  - "social_icons"
  - "t"

markdown: "kramdown"

kramdown:
  auto_ids: true
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"

plugins:
  - "jekyll-include-cache"
