# ====================
# Global configuration
# ====================
#
# See https://jekyllrb.com/docs/configuration/options/#global-configuration

source: "src"
destination: "_site"

include:

  # This file is used by Netlify to define redirects.  I also use it
  # to create the custom 404 page.
  #
  # Jekyll ignores files that start with an underscore, so I need to
  # include this explicitly.
  #
  # See https://docs.netlify.com/routing/redirects/
  - "_redirects"

# =====================
# Build command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#build-command-options

# This enables strict parsing of the YAML front matter.
strict_front_matter: true

# =====================
# Serve command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#serve-command-options

port: 5959
livereload: true

# ==============
# Liquid options
# ==============
#
# See https://jekyllrb.com/docs/configuration/liquid/

liquid:
  error_mode: strict
  strict_filters: true

  # Note: I deliberately omit `strict_variables: true` here, because
  # sometimes I want to be able to skip variables in the front matter
  # (e.g. I don't want to set an empty `nav_section: ""` for every page
  # which doesn't belong to a section).

# ================
# Permalink config
# ================
#
# Set the URL structure for permalinks on my posts.
# See https://jekyllrb.com/docs/permalinks/#global
permalink: "/:year/:title/"

# ==================
# Template variables
# ==================
#
# These variables aren't part of any third-party Jekyll plugin; they're
# placeholders used in my templates.

date_format: "%-d %B %Y"

# ================
# Remaining config

url: "https://books.alexwlchan.net"

exclude:
  - "covers"

keep_files:
  - "favicons"
  - "individual_covers"
  - "social_icons"
  - "thumbs"

includes_dir: "_jekyll/includes"
layouts_dir: "_jekyll/layouts"
plugins_dir:
  - "src/_jekyll/plugins"

markdown: "kramdown"

kramdown:
  auto_ids: true
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"

plugins:
  - "jekyll-include-cache"
