[build]
  base = ""
  publish = "_html/"

[[headers]]
  for = "/covers/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

[[headers]]
  for = "/static/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

[[headers]]
  for = "/thumbnails/*"

  [headers.values]
		cache-control = "public, max-age=31536000"
