[build]
  base = ""
  publish = "_site/"

# [[headers]]
#   for = "/individual_covers/*"
#
#   [headers.values]
#     cache-control = "public, max-age=31536000"
#
# [[headers]]
#   for = "/static/*"
#
#   [headers.values]
#     cache-control = "public, max-age=31536000"

[[headers]]
  for = "/thumbs/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

# [[headers]]
#   for = "/favicons/*"
#
#   [headers.values]
#     cache-control = "public, max-age=31536000"
#
# # I test my security headers with https://securityheaders.com/
# [[headers]]
#   for = "/*"
#
#   [headers.values]
#     # https://scotthelme.co.uk/hardening-your-http-response-headers/#content-security-policy
#     content-security-policy = """\
#       default-src ; \
#       style-src 'self' 'unsafe-inline'; \
#       img-src 'self' data:; \
#       script-src 'self' 'unsafe-inline' https://unpkg.com/; \
#       connect-src https://analytics.alexwlchan.net/; \
#     """
#
#     # https://scotthelme.co.uk/a-new-security-header-feature-policy/
#     # https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/
#     permissions-policy = """\
#       geolocation=(), \
#       midi=(), \
#       notifications=(), \
#       push=(), \
#       sync-xhr=(), \
#       microphone=(), \
#       camera=(), \
#       magnetometer=(), \
#       gyroscope=(), \
#       vibrate=(),
#       payment=() \
#     """
#
#     # https://scotthelme.co.uk/a-new-security-header-referrer-policy/
#     referrer-policy = "no-referrer-when-downgrade"
#
#     # https://scotthelme.co.uk/hardening-your-http-response-headers/#strict-transport-security
#     strict-transport-security = "max-age=31536000; includeSubDomains"
#
#     # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options
#     x-content-type-options = "nosniff"
#
#     # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options
#     x-frame-options = "DENY"
#
#     # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection
#     x-xss-protection = "1; mode=block"
