[build]
  base = ""
  publish = "_html/"
  command = "./netlify_deploy.sh"

[[headers]]
  for = "/covers/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

[[headers]]
  for = "/static/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

[[headers]]
  for = "/thumbnails/*"

  [headers.values]
		cache-control = "public, max-age=31536000"

# I test my security headers with https://securityheaders.com/
[[headers]]
  for = "/*"

  [headers.values]
    # https://scotthelme.co.uk/hardening-your-http-response-headers/#content-security-policy
    #
    #   - youtube-nocookie.com is used for YouTube embeds
    #
    content-security-policy = """\
      default-src ; \
      style-src 'self' 'unsafe-inline'; \
      img-src 'self' data:; \
    """

    # https://scotthelme.co.uk/a-new-security-header-feature-policy/
    # https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/
    permissions-policy = """\
      geolocation=(), \
      midi=(), \
      notifications=(), \
      push=(), \
      sync-xhr=(), \
      microphone=(), \
      camera=(), \
      magnetometer=(), \
      gyroscope=(), \
      vibrate=(),
      payment=() \
    """

    # https://scotthelme.co.uk/a-new-security-header-referrer-policy/
    referrer-policy = "no-referrer-when-downgrade"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#strict-transport-security
    strict-transport-security = "max-age=31536000; includeSubDomains"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-content-type-options
    x-content-type-options = "nosniff"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options
    x-frame-options = "DENY"

    # https://scotthelme.co.uk/hardening-your-http-response-headers/#x-xss-protection
    x-xss-protection = "1; mode=block"

[[headers]]
  for = "/2019/09/triangular-coordinates-in-svg/"

  [headers.values]
    # https://scotthelme.co.uk/hardening-your-http-response-headers/#content-security-policy
    #
    # These are specific overrides to allow MathJax to load on one page
    # where I'm using it.  I don't allow it on the broader site because
    # it's unnecessary and gets warnings on security header checks.
    content-security-policy = """\
      default-src 'self' 'unsafe-inline' \
      script-src 'self' 'unsafe-inline' \
      https://polyfill.io \
      https://cdn.jsdelivr.net \
      'unsafe-eval'; \
      font-src \
      https://polyfill.io \
      https://cdn.jsdelivr.net; \
      img-src 'self' 'unsafe-inline' data: \
    """