#!/usr/bin/env bash
# Copy an image from my open browser tab into my book tracker.
#
# == Usage ==
#
#   1. Create a Markdown file for a new review, for example
#      `src/_posts/2024/2024-06-17-a-great-book.md`
#   2. Find a cover image for the book in Safari
#   3. Run this script
#
# The script will work out the required name of the cover image
# (`src/covers/2024/a-great-book.jpg`) and download it.

set -o errexit
set -o nounset

LATEST_REVIEW=$(git ls-files -o --exclude-standard)

if [[ "$LATEST_REVIEW" = "" ]]
then
  echo "Please create the review file before you copy the cover image!" >&2
  exit 1
fi

print_info "-> Latest review is $LATEST_REVIEW"

# In Jekyll, post filenames are prefixed with a date in YYYY-MM-DD format,
# e.g. `src/_posts/2024/2024-06-17-a-great-book.md`.
#
# We want to remove the date prefix from the cover images, e.g. `a-great-book`,
# hence the `cut` command.
#
# In this example:
#
#   filename = a-great-book
#   year     = 2024
#
filename=$(basename -- "$LATEST_REVIEW" .md | cut -c 12-)
year=$(basename -- $(dirname -- "$LATEST_REVIEW"))

url=$(osascript -e 'tell application "Safari" to get URL of document 1')
print_info "-> Frontmost Safari URL is $url"

image_filename=$(basename -- "$url" | tr '?' ' ' | awk '{print $1}')
image_extension="${image_filename##*.}"

image_path=src/covers/$year/$filename.$image_extension

mkdir -p "$(dirname "$image_path")"

print_info "-> curl \"$url\" > \"$image_path\""
curl "$url" > "$image_path"
dominant_colours "$image_path"
