name: build_site

on:
  push:
    branches:
    - main

    paths-ignore:
      - '.github/workflows/rubocop.yml'
      - '.github/workflows/run_plugin_tests.yml'

  pull_request:
    branches:
    - main

    paths-ignore:
      - '.github/workflows/rubocop.yml'
      - '.github/workflows/run_plugin_tests.yml'

  # This daily rebuild is to avoid GitHub Actions purging the site cache,
  # because regenerating all the image thumbnails would be a PITA:
  #
  #     GitHub will remove any cache entries that have not been
  #     accessed in over 7 days.
  #
  # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
  schedule:
    - cron: "30 7 * * *"

jobs:
  build:
    name: Build the website
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: lint
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          cache-version: 1

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: "Cache site output"
        uses: "actions/cache@v4"
        with:
          path: _site
          key: "site-${{ github.sha }}"
          restore-keys: "site-"

      - name: "Cache the .jekyll-cache folder"
        uses: "actions/cache@v4"
        with:
          path: src/.jekyll-cache
          key: "jekyll-cache-${{ github.sha }}"
          restore-keys: "jekyll-cache-"

      - name: "Cache the .shelves folder"
        uses: "actions/cache@v4"
        with:
          path: src/.shelves
          key: "shelves-${{ github.sha }}"
          restore-keys: "shelves-"

      - name: "Set the JEKYLL_ENV variable"
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]
          then
            echo "JEKYLL_ENV=production" >> "$GITHUB_ENV"
          else
            echo "JEKYLL_ENV=development" >> "$GITHUB_ENV"
          fi

      - name: "Build the site"
        run: bundle exec jekyll build

      - name: "Run linting"
        run: bundle exec ruby scripts/linter.rb

      - name: Deploy to Linode
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > id_rsa
          rsync \
            --rsh="ssh -i id_rsa -o StrictHostKeychecking=no" \
            --archive \
            --compress \
            --verbose \
            --recursive \
            --progress \
            --delete \
            "_site/" "alexwlchan@alexwlchan.net:repos/books.alexwlchan.net/_site"
