name: build_site

on:
  push:
    branches:
    - main

    paths-ignore:
      - '.github/workflows/rubocop.yml'
      - '.github/workflows/run_plugin_tests.yml'

  pull_request:
    branches:
    - main

    paths-ignore:
      - '.github/workflows/rubocop.yml'
      - '.github/workflows/run_plugin_tests.yml'

  # This daily rebuild is to avoid GitHub Actions purging the site cache,
  # because regenerating all the image thumbnails would be a PITA:
  #
  #     GitHub will remove any cache entries that have not been
  #     accessed in over 7 days.
  #
  # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
  schedule:
    - cron: "30 7 * * *"

jobs:
  build:
    name: Build the website
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: lint
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          cache-version: 1

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: "Cache site output"
        uses: "actions/cache@v4"
        with:
          path: _site
          key: "site-${{ github.sha }}"
          restore-keys: "site-"

      - name: "Cache the .jekyll-cache folder"
        uses: "actions/cache@v4"
        with:
          path: src/.jekyll-cache
          key: "jekyll-cache-${{ github.sha }}"
          restore-keys: "jekyll-cache-"

      - name: "Cache the .shelves folder"
        uses: "actions/cache@v4"
        with:
          path: src/.shelves
          key: "shelves-${{ github.sha }}"
          restore-keys: "shelves-"

      - name: "Set the JEKYLL_ENV variable"
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]
          then
            echo "JEKYLL_ENV=production" >> "$GITHUB_ENV"
          else
            echo "JEKYLL_ENV=development" >> "$GITHUB_ENV"
          fi

      - name: "Build the site"
        run: bundle exec jekyll build

      - name: "Run linting"
        run: bundle exec ruby scripts/linter.rb

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "_site"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-commit-comment: false
          enable-pull-request-comment: false
          overwrites-pull-request-comment: true
          netlify-config-path: netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "66a899f3-16ae-42af-b059-db28a1fbc731"
        timeout-minutes: 1
