name: build_site

on:
  push:
    branches:
    - main

    paths-ignore:
      - '.github/workflows/rubocop.yml'
      - '.github/workflows/run_plugin_tests.yml'

  pull_request:
    branches:
    - main

    paths-ignore:
      - '.github/workflows/rubocop.yml'
      - '.github/workflows/run_plugin_tests.yml'

  schedule:
    - cron: "30 7 * * *"

jobs:
  build:
    name: Build the website
    runs-on: self-hosted
    
    env:
      # This tells `bundle install` to install gems in a user-owned directory,
      # so it doesn't need sudo permissions.
      GEM_HOME: /home/alexwlchan/.gems
    
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v5
        with:
          # Don't run `git clean/reset` when checking out the repo.
          #
          # This means the existing copy of the `_site` folder is preserved,
          # so the site doesn't have to be rebuilt from scratch every time.
          clean: false

      - name: "Install Ruby dependencies"
        run: bundle install

      - name: "Set the JEKYLL_ENV variable"
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]
          then
            echo "JEKYLL_ENV=production" >> "$GITHUB_ENV"
          else
            echo "JEKYLL_ENV=development" >> "$GITHUB_ENV"
          fi

      - name: "Build the site"
        run: bundle exec jekyll build

      - name: "Run linting"
        run: bundle exec ruby scripts/linter.rb

      - name: Copy to the public directory
        if: github.ref == 'refs/heads/main'
        run: |
          rsync \
            --compress \
            --recursive \
            --delete \
            --verbose \
            --checksum \
            --exclude="" \
            --include="" \
            --filter="" \
            _site/ \
            ~/repos/books.alexwlchan.net/_site/
