name: "plugin-tests"

on:
  push:
    branches:
    - main

    paths:
      - 'src/_plugins/**'
      - 'src/_tests/**'
      - 'Gemfile'
      - 'Gemfile.lock'

  pull_request:
    branches:
    - main

    paths:
      - 'src/_plugins/**'
      - 'src/_tests/**'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  build:
    name: Run plugin tests
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: test
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cache-version: 1

      - name: "Run the plugin tests"
        run: bundle exec ruby src/_tests/tests.rb
